# System
gpu_num: 1
seed: 42
debug: False
verbose: False

# Wandb
project_name : "voice2face"
run_name : "ldm"
wandb_note : "ldm"

mlflow_exp_name : "xp"
# Train / val
val_size: 0.2

# Data Loader
dataset_name : SegDataset
input_width: 480
input_height: 256
scaler: normalize
num_workers: 4
shuffle: True
drop_last: False

# Model
model:
  timesteps: 500
  scheduler_name: linear
  model_name: UNET
    args:
      image_channels: 3
      model_channels: 64 
      num_res_blocks: 4
      num_heads: 4
      dim_head: 32
      dropout: 0.1
  model_name: SF2F
    args: 
  model_name: VQVAE
    args:
      img_channels: 3
      init_planes: 
      planes_mults:
      resnet_groups:
      resnet_stacks:
      up_mode:
      scale:
      attention:
      attn_heads:
      attn_dim:
      latent_dim:
      eps:
      legacy_mid:
      tanh_out:
      num_embeddings: 256
      z_channels: 32
      commitment_cost: 0.2
      

# Trainer
n_epochs: 100
batch_size: 16
loss: 
  name: MeanCCELoss # MeanCCELoss
  args:
    weight: [1, 1, 1, 1]
metrics: 
  - miou
  - iou1
  - iou2
  - iou3
earlystopping_target: val_miou
earlystopping_patience: 5
optimizer:
  name: AdamW
  args:
    lr: 5.0e-04
    weight_decay: 5.0e-02
scheduler:
  name: CosineAnnealingLR
  args:
    T_max: 100
    eta_min: 0

# Logging
plot:
  - loss
  - miou
  - iou1
  - iou2
  - iou3
